services:
  traefik:
    image: traefik:${VERSION_T:-v3.3}
    container_name: ${PROJECT_NAME:-traefik}
    restart: unless-stopped
    ports:
      - "${FORWARD_PORT_HTTP:-80}:80"
      - "${FORWARD_PORT_HTTPS:-443}:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_certificates:/letsencrypt
    command:
      - "--log.level=INFO"
      - "--log.format=common"
      - "--accesslog=true"
      - "--accesslog.format=json"
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=${PROJECT_NAME:-traefik}_public_network"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.${RESOLVER_NAME:-myresolver}.acme.tlschallenge=true"
      - "--certificatesresolvers.${RESOLVER_NAME:-myresolver}.acme.email=${ACME_EMAIL:-admin@localhost.local}"
      - "--certificatesresolvers.${RESOLVER_NAME:-myresolver}.acme.storage=/letsencrypt/acme.json"
    networks:
      - network_stack

volumes:
  traefik_certificates:
    name: ${PROJECT_NAME:-traefik}_certificates

networks:
  network_stack:
    name: ${PROJECT_NAME:-traefik}_public_network
    external: true